# Generated by Django 5.1.6 on 2025-04-02 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='genere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=300)),
                ('likes', models.FloatField()),
                ('share', models.FloatField()),
                ('dislike', models.FloatField()),
                ('Rating', models.FloatField()),
                ('image', models.ImageField(upload_to='static/movies')),
                ('poster', models.CharField(max_length=700)),
                ('release_date', models.DateField()),
                ('category', models.ManyToManyField(related_name='movies', to='api.genere')),
                ('language', models.ManyToManyField(related_name='lang', to='api.language')),
            ],
        ),
    ]
