# Generated by Django 5.1.7 on 2025-04-12 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_movies_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='image',
        ),
    ]
