# Generated by Django 5.1.7 on 2025-05-07 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_movies_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movies',
            name='is_trending',
            field=models.BooleanField(default=False),
        ),
    ]
