# Generated by Django 5.1.7 on 2025-05-29 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_movies_is_popular_movies_is_trending'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='banner',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='movies',
            name='is_banner',
            field=models.BooleanField(default=False),
        ),
    ]
